language: generic
env:
  - PATH=$HOME/google-cloud-sdk/bin:$HOME/miniconda3/bin:$PATH
cache:
  directories:
    - $HOME/google-cloud-sdk
    - $HOME/miniconda3
    - $HOME/miniconda3_installer
  timeout: 1000 # this gives travis-CI sufficient time (up to ~16 minutes) to cache large conda directories
before_install:
  - ./bin/setup.sh
jobs:
  include: 
    - stage: train model
      script:
      - ./bin/get_data.sh
      - ./bin/train.sh scikit-model
      - ./bin/evaluate.sh scikit-model
    - stage: deploy model
      script:
      - ./bin/deploy.sh scikit-model
      - echo 'smoke test for staging'
#     - stage: deploy model to production
#       if: branch = deploy-to-prod
#       script: echo "initiate deploy-to-prod job"
#     - stage: smoke test for production
#       if: branch = deploy-to-prod
#       script: echo "running smoke test"
