language: generic
env:
  global:
  - PATH=$HOME/google-cloud-sdk/bin:$HOME/miniconda3/bin:$PATH CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
  - "$HOME/google-cloud-sdk"
  - "$HOME/miniconda3"
  - "$HOME/miniconda3_installer"
  timeout: 1000
before_install:
- openssl aes-256-cbc -K $encrypted_64a1b7c39bac_key -iv $encrypted_64a1b7c39bac_iv
  -in gcp_ml_ci_cd_demo.json.enc -out ./gcp_ml_ci_cd_demo.json -d
- ./bin/setup.sh
jobs:
  include:
  - stage: unit tests
    script:
    - ./bin/run_unit_tests.sh scikit-model
  - stage: train and evaluate model
    if: branch = deploy-to-staging
    script:
    - ./bin/get_data.sh
    - ./bin/train.sh scikit-model
    - ./bin/evaluate.sh scikit-model
    - ./bin/upload_artifact.sh scikit-model
  - stage: deploy candidate model to staging
    if: branch = deploy-to-staging
    script:
    - ./bin/deploy_to_staging.sh scikit-model
    - echo 'smoke test for staging'
  - stage: deploy model to prod
    if: branch = deploy-to-prod
    script:
    - ./bin/deploy_to_prod.sh scikit-model $(cat ./bin/MODEL_PROD_VERSION.txt)
