name: ml-ci-cd-demo
dependencies:
  - python=3.6
  - pandas=0.19.2
  - numpy
  - matplotlib=2.0.0
  - scikit-learn
  - jupyter=1.0.0
  - scipy
  - nose==1.3.7
  - pip:
    - imblearn
    - google-api-python-client
    - tensorflow==1.7.0
    - tensorflow-tensorboard==1.5.1 
