name: ml-ci-cd-demo
dependencies:
  - python=3.6
  - pandas=0.19.2
  - numpy
  - matplotlib=2.0.0
  - scikit-learn
  - jupyter=1.0.0
  - scipy
  # - google-api-core=0.1.4
  # - google-api-python-client=1.6.2
  # - google-auth=1.3.0
  # - google-auth-httplib2=0.0.2
  # - google-auth-oauthlib=0.1.0
  # - google-cloud=0.30.0
  # - google-cloud-bigquery=0.28.0
  # - google-cloud-bigtable=0.28.1
  # - google-cloud-core=0.28.0
  # - google-cloud-datastore=1.4.0
  # - google-cloud-dns=0.28.0
  # - google-cloud-error-reporting=0.28.0
  # - google-cloud-firestore=0.28.0
  # - google-cloud-language=1.0.0
  # - google-cloud-logging=1.4.0
  # - google-cloud-monitoring=0.28.0
  # - google-cloud-pubsub=0.29.4
  # - google-cloud-resource-manager=0.28.0
  # - google-cloud-runtimeconfig=0.28.0
  # - google-cloud-spanner=0.29.0
  # - google-cloud-speech=0.30.0
  # - google-cloud-storage=1.6.0
  # - google-cloud-trace=0.16.0
  # - google-cloud-translate=1.3.0
  # - google-cloud-videointelligence=0.28.0
  # - google-cloud-vision=0.28.0
  # - google-gax=0.15.16
  # - google-resumable-media=0.3.1
  - pip:
    - imblearn
    - google-api-python-client
    - tensorflow==1.7.0
    - tensorflow-tensorboard==1.5.1 
